# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wJqL8T2tTPjjWonoiv34VRTWFCr7fGwB

**Question0**
 list=append(),pop(),index(),remove(),sort()
  string=isalnum(),isalpha(),index(),isdigit(),isnumeric()
  set=add(),clear(),copy()
  tuple=count(),index()
  dictionary=keys(),pop(),update(),values()
  files=close(),write(),read(),seek(),truncate()
"""

#question1
def aev(x,y):
    return y+x[::-1]
x=input()
y=input()
print(aev(x,y))

#question2
work_hours= [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]
def find_longest_and_addpay(l):
  max=[]
  for i in l:
    if max==[] or i[1]>max[1]:
      max=i
  print(max)
  g="female" if max[2].lower()=='f' else 'Male'
  return f"{max[0]} gets paid ${max[1]*20} Gender is {g} "
find_longest_and_addpay(work_hours)

#question3a
import numpy as np
a = np.array([[1],[2],[3],[4],[5]])
b = np.array([[1],[2],[3],[4],[5]])
c = np.array([[1],[2],[3],[4],[5]])
d = np.array([[1],[2],[3],[4],[5]])
e = np.array([[1],[2],[3],[4],[5]])
np.hstack((a,b,c,d,e))

#question3b
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)